version: "3.3"

services:
  app:
    image: app:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: streamlit run /usr/src/app/Home.py
    volumes:
      - ../:/usr/src/app/
    ports:
      - 8501:8501
      # - 10001:10001
    environment:
      - TESTING=0
      - ENVIRONMENT=dev

      - DEBUGGER=False
